[package]
name = "axion-consulta"
version = "1.0.0"
description = "Consulta de Medicamentos AXION"
authors = ["Alef"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postgres = "0.19"
